apiVersion: v1
kind: Service
metadata:
  name: tcp-service
  namespace: default
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  # loadBalancerIP: 10.10.20.250
  selector:
    lbtype: external
  ports:
  - name: 8000-to-8000
    protocol: TCP
    port: 8000
    targetPort: "8000-port"
  - name: 8001-to-8001
    protocol: TCP
    port: 8001
    targetPort: "8000-port"
  - name: 8002-to-8100
    protocol: TCP
    port: 8002
    targetPort: "8100-port"
